### ISSUE TITLE
identify_crispr.py TypeError: argument should be integer or bytes-like object, not 'str'

### ISSUE THREAD

**Issue by emily-ebel** [snayfach/MGV#14]
Hello, and thanks for this great viral detection pipeline! Earlier steps worked seamlessly for me. 

Running the example code `python identify_crispr.py -i example/GUT_GENOME147678.fna -o out` in a cloned repository gives me the following error:

Traceback (most recent call last):
  File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 485, in <module>
    arrays = run_pipeline(args, offsets, append_ns=50, program=program)
  File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 405, in run_pipeline
    my_arrays = parse_crt(out, contigs)
  File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 108, in parse_crt
    if out.find('\nCRISPR') == -1:
TypeError: argument should be integer or bytes-like object, not 'str'

The `out` directory contains one file, `out/temp/seqs/0d239010-1666-403a-9b21-f06c24f1d762`, which is a fasta with the 50 Ns at either end. 

I'm not overly skilled at Python, but adding some print commands let me see the output of 

`out, err, code = run_crt(tmp_path, args['tempdir'], xmx=args['xmx'])`. 

`out`, which seems to be causing the problem, prints like it's a big string...

b'\n\nReading file out/temp/seqs/17b75e28-a677-44b1-bc28-e9d7592c72e4\nReading file complete\ntmpfile\n2833987 bases\nSearching for repeats...\nTime to search for repeats:  453 ms\n2 possible CRISPR(s) found\n\nORGANISM:  tmpfile\nBases: 2833987\n\n\nCRISPR 1   Range: 682229 - 685495\nPOSITION\tREPEAT\t\t\t\tSPACER\n--------\t----
-----------------------------\t----------------------------------\n682229\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAATAATCCAGTGCTCATTTTTTGATCTCCTTCGGT\t[ 33, 35 ]
\n682297\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tATTCCATTTTACATTCCTATGCACTTAGGAGACCC\t[ 33, 35 ]\n682365\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAAGACAGTTGCAACGCGATTGATGCCGGAAGAAT\t[ 33, 34 ]\n682432\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCGATCTGGAAAACAATGTGTATGAGACGAACGA\t[ 33, 33 ]\n682498\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCTGCGTCTGCGGCCGGAGCATACCGAAGCTCACGTG\t[ 33, 36 ]\n682567\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCGCCTCCGGTGCGCTGTTGCCGTCGTACAGCGTCG\t[ 33, 35 ]\n682635\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTGCTCCGATTTAATGCACCGGACCGCATACCGG\t[ 33, 33 ]\n682701\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAGCCGCTCTATCGGGACGTTCCGCAGCCCGGACCG\t[ 33, 35 ]\n682769\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tATAAGCAGCCTGCGGGTCAGGGAACAGACCGGGCG\t[ 33, 35 ]\n682837\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTCGCTACCAGTGGCACTAGGCATGGCAGTCAGGCT\t[ 33, 35 ]\n682905\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTCTTGTGTCTCCTTCGATAACGCCCTTGCATCTGT\t[ 33, 35 ]\n682973\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCTCAGTCGTACGGCTCAGTGAGCAAGAGCTGAG\t[ 33, 33 ]\n683039\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTTTTCCAGGCCGCACTCCACCATCTTGCTGCTGGCC\t[ 33, 36 ]\n683108\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACAAATGAAACGGGTAAAAAATTAGTTGGAAATG\t[ 33, 34 ]\n683175\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAATCAGGATAACACCCTTGCAGACACGCTTATCC\t[ 33, 34 ]\n683242\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGACGAACGCAACGGCAATTTCGAGGAAGCAAAGGA\t[ 33, 35 ]\n683310\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCTCCTTGTCATGTAGCGCGTGATAAATCGCGTCC\t[ 33, 34 ]\n683377\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCCGTTCTTCCCGAAAGAAACGGCAGACCAGTTGG\t[ 33, 34 ]\n683444\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCCACCCGGCGGGCATAGGCCGCGCTGGCAAGAGC\t[ 33, 36 ]\n683513\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGTAAGAAGAAGCTCGGTGCAATCAAAATCGGAAAG\t[ 33, 35 ]\n683581\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGTCATCAGAGTAGCGGACGGCAAAGTAGCCGCCG\t[ 33, 35 ]\n683649\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCCAGCTCAGGCGCTCAGTGTTGATACCTGCAT\t[ 33, 34 ]\n683716\t\tGTCGCCCTCCTCGCAGAGGGCGTGGATAGAAAT\tACCTCATAGCCTTTGCCAAGCGTCGCGTCGCAA\t[ 33, 33 ]\n683782\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGGGTCAAACTTGAGGCCGTCCCGGTAGCCCTTC\t[ 33, 33 ]\n683848\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGCGGTGCAGGCTCAACCACGGTGGGAGTGCTGG\t[ 33, 34 ]\n683915\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGCGAGCTTTACAGCATCCCGGCATGAACGCCG\t[ 33, 33 ]\n683981\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCTGCTGGCTCGGCTCAACGCCCAGCGGCATCCCA\t[ 33, 34 ]\n684048\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTTTGCGTTGTACCGCGCCGGTCCTGCGACGGCG\t[ 33, 33 ]\n684114\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCCCCCAAGCGTGTGGTAGCTGCGATAGAGGTACT\t[ 33, 34 ]\n684181\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGTGCGCTGCGCCGCTCCGGTGCAGGCAGGTCAA\t[ 33, 34 ]\n684248\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACCCACGGACGGGAGCTCACATGGCAACCCTCAG\t[ 33, 34 ]\n684315\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGGCTGTTGTAGTCGCTGAATACGCCGCTCCGGC\t[ 33, 34 ]\n684382\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTACTCTCGTCGTGGATGCAATACCTACAATTTTT\t[ 33, 34 ]\n684449\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGCCTCGTCACGGGTCAGATGCGGATGCGGCATC\t[ 33, 34 ]\n684516\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATGTACCCGTTAGCAAAGGCCACCAGGCCGTTAGT\t[ 33, 35 ]\n684584\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATATTATCATTGATCGTATGAAGAGATCCAGAAATA\t[ 33, 36 ]\n684653\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACGACAACAGCATACTTTCGCACACCACGGCGG\t[ 33, 33 ]\n684719\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTCGTGGTGGCCTTGCCCATATCCAGTGCTGCTTG\t[ 33, 34 ]\n684786\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTCGCTGGCCAGAGGGCAGCCATGCGCACTGCATC\t[ 33, 34 ]\n684853\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCAGACCGAAAGCATCCAACCAGTCGAAGAAGTC\t[ 33, 35 ]\n684921\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGACCTCGAAGCTGCAGGCAGTTTACCGCAAGTTT\t[ 33, 35 ]\n684989\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACGCTGTATTTACGGTTGGATAGCTGGCTGATTTG\t[ 33, 35 ]\n685057\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGACGGCAAGACCCAGCGCGTGGATGACCTCTTT\t[ 33, 34 ]\n685124\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATGAGAAGCTGGGCATCAAGGATAAGTATACCGAT\t[ 33, 35 ]\n685192\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTTCGATCTTCTCGCGCAGATGGAACGGCTCATAGGC\t[ 33, 36 ]\n685261\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGGCCAGCCTGACCCTCCAGACCCGCCGCAGAAC\t[ 33, 34 ]\n685328\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGGCAAGAAGTTTGGCTTCGCACTGGATGTTCTCAC\t[ 33, 35 ]\n685396\t\tGTCGCCTTCCTCGCGGAGGGCGTGGATAGAAAT\tACCGCATAACCCCACTGGAAAACGCCATCACGCA\t[ 33, 34 ]\n685463\t\tGTCGCCCTCCTCGCGGAGGGCGCAAGTAGAAAT\t\n--------\t---------------------------------\t----------------------------------\nRepeats: 49\tAverage Length: 33\t\tAverage Length: 34\n\n\n\nCRISPR 2   Range: 1072592 - 1073272\nPOSITION\tREPEAT\t\t\t\tSPACER\n--------\t--------------------------------\t--------------------------------\n1072592\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGCGAGAGCATAGAAGATGAGCTGTCCGACCTCG\t[ 32, 33 ]\n1072657\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tTCCCCGGTGCAGCCCCGGCGGATGGTCGGCAGAAT\t[ 32, 35 ]\n1072724\t\tATTGCAGTTTATCCCCGCAAGGGGACGATAAC\tAGAACTGCAGTATGGATGTCGTTCACGCGGTAG\t[ 32, 33 ]\n1072789\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tATCAAAGATCTTTCTAAACTCCTCGATATCGTA\t[ 32, 33 ]\n1072854\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGAGCAAGTGCTTTCTGTTCGTCGTAAGTCATCAC\t[ 32, 34 ]\n1072920\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tATCAAAGATCTTTCTAAACTCCTCGATATCGTA\t[ 32, 33 ]\n1072985\t\tATTGCAGCTTATCCCTGCAAGGGGACGATAAT\tTTCACTTTCTTGATCTGCTTCTTTTCGGCACGG\t[ 32, 33 ]\n1073050\t\tATTGCAGCTTATCCCCGCAAAGGGACGATAAC\tGTCACAGCTTGCTGCTTGTCCAGTTTGGCGTCC\t[ 32, 33 ]\n1073115\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGACCTTTGCCATTGCCTTCTTGTCCTTGCGGCTC\t[ 32, 34 ]\n1073181\t\tATTGCAGCTTATCCCCGCAAGGGGGCGAAAAC\tAAACTCCATTCTTATTTCAGATTAAATA\t[ 32, 28 ]\n1073241\t\tAATAAGTACCATCCCCGTAAGGGGGCAAAAAC\t\n--------\t--------------------------------\t--------------------------------\nRepeats: 11\tAverage Length: 32\t\tAverage Length: 32\n\n\n\nTime to find repeats: 453 ms\n\n\n\n'

...but if I try to write `out` to file, just before `if out.find('\nCRISPR') == -1`,  I get:

 TypeError: write() argument must be str, not bytes

Any help would be much appreciated! Thank you :)

**Comment by qinjunjun** [comment]
> Hello, and thanks for this great viral detection pipeline! Earlier steps worked seamlessly for me.
> 
> Running the example code `python identify_crispr.py -i example/GUT_GENOME147678.fna -o out` in a cloned repository gives me the following error:
> 
> Traceback (most recent call last): File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 485, in arrays = run_pipeline(args, offsets, append_ns=50, program=program) File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 405, in run_pipeline my_arrays = parse_crt(out, contigs) File "/home/ebel/user_data/FeFiFo/MGV/crispr_spacers/identify_crispr.py", line 108, in parse_crt if out.find('\nCRISPR') == -1: TypeError: argument should be integer or bytes-like object, not 'str'
> 
> The `out` directory contains one file, `out/temp/seqs/0d239010-1666-403a-9b21-f06c24f1d762`, which is a fasta with the 50 Ns at either end.
> 
> I'm not overly skilled at Python, but adding some print commands let me see the output of
> 
> `out, err, code = run_crt(tmp_path, args['tempdir'], xmx=args['xmx'])`.
> 
> `out`, which seems to be causing the problem, prints like it's a big string...
> 
> b'\n\nReading file out/temp/seqs/17b75e28-a677-44b1-bc28-e9d7592c72e4\nReading file complete\ntmpfile\n2833987 bases\nSearching for repeats...\nTime to search for repeats: 453 ms\n2 possible CRISPR(s) found\n\nORGANISM: tmpfile\nBases: 2833987\n\n\nCRISPR 1 Range: 682229 - 685495\nPOSITION\tREPEAT\t\t\t\tSPACER\n--------\t---- -----------------------------\t----------------------------------\n682229\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAATAATCCAGTGCTCATTTTTTGATCTCCTTCGGT\t[ 33, 35 ] \n682297\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tATTCCATTTTACATTCCTATGCACTTAGGAGACCC\t[ 33, 35 ]\n682365\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAAGACAGTTGCAACGCGATTGATGCCGGAAGAAT\t[ 33, 34 ]\n682432\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCGATCTGGAAAACAATGTGTATGAGACGAACGA\t[ 33, 33 ]\n682498\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCTGCGTCTGCGGCCGGAGCATACCGAAGCTCACGTG\t[ 33, 36 ]\n682567\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCGCCTCCGGTGCGCTGTTGCCGTCGTACAGCGTCG\t[ 33, 35 ]\n682635\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTGCTCCGATTTAATGCACCGGACCGCATACCGG\t[ 33, 33 ]\n682701\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tAGCCGCTCTATCGGGACGTTCCGCAGCCCGGACCG\t[ 33, 35 ]\n682769\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tATAAGCAGCCTGCGGGTCAGGGAACAGACCGGGCG\t[ 33, 35 ]\n682837\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTCGCTACCAGTGGCACTAGGCATGGCAGTCAGGCT\t[ 33, 35 ]\n682905\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTCTTGTGTCTCCTTCGATAACGCCCTTGCATCTGT\t[ 33, 35 ]\n682973\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tCTCAGTCGTACGGCTCAGTGAGCAAGAGCTGAG\t[ 33, 33 ]\n683039\t\tGTCGCCCTCCTTGCGGAGGGCGTGGATAGAAAT\tTTTTCCAGGCCGCACTCCACCATCTTGCTGCTGGCC\t[ 33, 36 ]\n683108\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACAAATGAAACGGGTAAAAAATTAGTTGGAAATG\t[ 33, 34 ]\n683175\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAATCAGGATAACACCCTTGCAGACACGCTTATCC\t[ 33, 34 ]\n683242\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGACGAACGCAACGGCAATTTCGAGGAAGCAAAGGA\t[ 33, 35 ]\n683310\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCTCCTTGTCATGTAGCGCGTGATAAATCGCGTCC\t[ 33, 34 ]\n683377\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCCGTTCTTCCCGAAAGAAACGGCAGACCAGTTGG\t[ 33, 34 ]\n683444\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCCACCCGGCGGGCATAGGCCGCGCTGGCAAGAGC\t[ 33, 36 ]\n683513\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGTAAGAAGAAGCTCGGTGCAATCAAAATCGGAAAG\t[ 33, 35 ]\n683581\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGTCATCAGAGTAGCGGACGGCAAAGTAGCCGCCG\t[ 33, 35 ]\n683649\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCCAGCTCAGGCGCTCAGTGTTGATACCTGCAT\t[ 33, 34 ]\n683716\t\tGTCGCCCTCCTCGCAGAGGGCGTGGATAGAAAT\tACCTCATAGCCTTTGCCAAGCGTCGCGTCGCAA\t[ 33, 33 ]\n683782\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGGGTCAAACTTGAGGCCGTCCCGGTAGCCCTTC\t[ 33, 33 ]\n683848\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGCGGTGCAGGCTCAACCACGGTGGGAGTGCTGG\t[ 33, 34 ]\n683915\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGCGAGCTTTACAGCATCCCGGCATGAACGCCG\t[ 33, 33 ]\n683981\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCTGCTGGCTCGGCTCAACGCCCAGCGGCATCCCA\t[ 33, 34 ]\n684048\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTTTGCGTTGTACCGCGCCGGTCCTGCGACGGCG\t[ 33, 33 ]\n684114\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCCCCCAAGCGTGTGGTAGCTGCGATAGAGGTACT\t[ 33, 34 ]\n684181\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGTGCGCTGCGCCGCTCCGGTGCAGGCAGGTCAA\t[ 33, 34 ]\n684248\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACCCACGGACGGGAGCTCACATGGCAACCCTCAG\t[ 33, 34 ]\n684315\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tAGGCTGTTGTAGTCGCTGAATACGCCGCTCCGGC\t[ 33, 34 ]\n684382\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTACTCTCGTCGTGGATGCAATACCTACAATTTTT\t[ 33, 34 ]\n684449\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGCCTCGTCACGGGTCAGATGCGGATGCGGCATC\t[ 33, 34 ]\n684516\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATGTACCCGTTAGCAAAGGCCACCAGGCCGTTAGT\t[ 33, 35 ]\n684584\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATATTATCATTGATCGTATGAAGAGATCCAGAAATA\t[ 33, 36 ]\n684653\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACGACAACAGCATACTTTCGCACACCACGGCGG\t[ 33, 33 ]\n684719\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTCGTGGTGGCCTTGCCCATATCCAGTGCTGCTTG\t[ 33, 34 ]\n684786\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTCGCTGGCCAGAGGGCAGCCATGCGCACTGCATC\t[ 33, 34 ]\n684853\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATCAGACCGAAAGCATCCAACCAGTCGAAGAAGTC\t[ 33, 35 ]\n684921\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGACCTCGAAGCTGCAGGCAGTTTACCGCAAGTTT\t[ 33, 35 ]\n684989\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tACGCTGTATTTACGGTTGGATAGCTGGCTGATTTG\t[ 33, 35 ]\n685057\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTGACGGCAAGACCCAGCGCGTGGATGACCTCTTT\t[ 33, 34 ]\n685124\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tATGAGAAGCTGGGCATCAAGGATAAGTATACCGAT\t[ 33, 35 ]\n685192\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tTTCGATCTTCTCGCGCAGATGGAACGGCTCATAGGC\t[ 33, 36 ]\n685261\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tCGGCCAGCCTGACCCTCCAGACCCGCCGCAGAAC\t[ 33, 34 ]\n685328\t\tGTCGCCCTCCTCGCGGAGGGCGTGGATAGAAAT\tGGCAAGAAGTTTGGCTTCGCACTGGATGTTCTCAC\t[ 33, 35 ]\n685396\t\tGTCGCCTTCCTCGCGGAGGGCGTGGATAGAAAT\tACCGCATAACCCCACTGGAAAACGCCATCACGCA\t[ 33, 34 ]\n685463\t\tGTCGCCCTCCTCGCGGAGGGCGCAAGTAGAAAT\t\n--------\t---------------------------------\t----------------------------------\nRepeats: 49\tAverage Length: 33\t\tAverage Length: 34\n\n\n\nCRISPR 2 Range: 1072592 - 1073272\nPOSITION\tREPEAT\t\t\t\tSPACER\n--------\t--------------------------------\t--------------------------------\n1072592\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGCGAGAGCATAGAAGATGAGCTGTCCGACCTCG\t[ 32, 33 ]\n1072657\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tTCCCCGGTGCAGCCCCGGCGGATGGTCGGCAGAAT\t[ 32, 35 ]\n1072724\t\tATTGCAGTTTATCCCCGCAAGGGGACGATAAC\tAGAACTGCAGTATGGATGTCGTTCACGCGGTAG\t[ 32, 33 ]\n1072789\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tATCAAAGATCTTTCTAAACTCCTCGATATCGTA\t[ 32, 33 ]\n1072854\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGAGCAAGTGCTTTCTGTTCGTCGTAAGTCATCAC\t[ 32, 34 ]\n1072920\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tATCAAAGATCTTTCTAAACTCCTCGATATCGTA\t[ 32, 33 ]\n1072985\t\tATTGCAGCTTATCCCTGCAAGGGGACGATAAT\tTTCACTTTCTTGATCTGCTTCTTTTCGGCACGG\t[ 32, 33 ]\n1073050\t\tATTGCAGCTTATCCCCGCAAAGGGACGATAAC\tGTCACAGCTTGCTGCTTGTCCAGTTTGGCGTCC\t[ 32, 33 ]\n1073115\t\tATTGCAGCTTATCCCCGCAAGGGGACGATAAC\tGACCTTTGCCATTGCCTTCTTGTCCTTGCGGCTC\t[ 32, 34 ]\n1073181\t\tATTGCAGCTTATCCCCGCAAGGGGGCGAAAAC\tAAACTCCATTCTTATTTCAGATTAAATA\t[ 32, 28 ]\n1073241\t\tAATAAGTACCATCCCCGTAAGGGGGCAAAAAC\t\n--------\t--------------------------------\t--------------------------------\nRepeats: 11\tAverage Length: 32\t\tAverage Length: 32\n\n\n\nTime to find repeats: 453 ms\n\n\n\n'
> 
> ...but if I try to write `out` to file, just before `if out.find('\nCRISPR') == -1`, I get:
> 
> TypeError: write() argument must be str, not bytes
> 
> Any help would be much appreciated! Thank you :)

you can use python2 , python3 maybe  make a mistake.

**Comment by snayfach** [comment]
Yes, please try with python 2

**Comment by emily-ebel** [comment]
Thanks to both of you!  To anyone who may run into this later, I had to use a conda environment without Python 3 and install Python 2.7 and v1.76 of Biopython. But then it worked!
